-- MySQL Script generated by MySQL Workbench
-- Tue Jul 10 07:06:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `direct2guests_beta` DEFAULT CHARACTER SET utf8 ;
USE `direct2guests_beta` ;

-- -----------------------------------------------------
-- Table `mydb`.`vodMovies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `direct2guests_beta`.`vodMovies` (
  `vod_id` INT NOT NULL AUTO_INCREMENT,
  `group` VARCHAR(50) NULL,
  `category` VARCHAR(50) NULL,
  `type` VARCHAR(50) NULL,
  `description` VARCHAR(500) NULL,
  `sources` VARCHAR(200) NULL,
  `card` VARCHAR(200) NULL,
  `background` VARCHAR(200) NULL,
  `title` VARCHAR(45) NULL,
  `studio` VARCHAR(45) NULL,
  PRIMARY KEY (`vod_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
